language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

# Note: we explicitly use a 'symfony 3' scenario here because we
# pin to Symfony Console 3.2.2 in our composer.lock for Apveyor testing.
# We can remove this once we fix the whitespace problem in the Windows tests.
matrix:
  include:
    - php: 7.2
      env: 'SCENARIO=symfony4 DEPENDENCIES=highest'
    - php: 7.1
      env: 'SCENARIO=symfony4'
    - php: 7.0.11
      env: 'SCENARIO=symfony3 DEPENDENCIES=highest'
    - php: 7.0.11
      env: 'SCENARIO=symfony3'
    - php: 5.6
      env: 'SCENARIO=symfony3'
    - php: 5.5
      env: 'SCENARIO=symfony2'
    - php: 5.4
      env: 'SCENARIO=symfony2 DEPENDENCIES=lowest'

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - 'composer scenario "${SCENARIO}" "${DEPENDENCIES-lock}"'

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls -v
