language: php
dist: trusty

branches:
  # Only test the main branch and SemVer tags.
  only:
    - main
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  include:
    - php: 7.4
      env: 'SCENARIO=symfony4 DEPENDENCIES=highest'
    - php: 7.4
    - php: 7.3
    - php: 7.2
    - php: 7.1
      env: 'SCENARIO=symfony4 DEPENDENCIES=lowest'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - './.scenarios.lock/install "${SCENARIO}" "${DEPENDENCIES}"'

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls -v
